export enum SessionHistoryEventType {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REFRESH = 'REFRESH',
  INVALIDATE = 'INVALIDATE',
  REVOKE = 'REVOKE',
  EXPIRE = 'EXPIRE',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
